---
pipeline_type: postgres_merge_upsert
pipeline_key: unit
pipeline_dag_configs:
  start_date: 2021-09-01 15:00:00
  schedule_interval: "0 15 * * *"

postgres:
  conn_id: analytics_db

execution_delay_seconds: 3600

upstream_dependencies:
- dag_id: postgres_merge_upsert_ad_lineitem
  timedelta_seconds: 0

merge_upsert:
  destination_table: unit
  staging_table: unit_staging
  unique_keys: 
  - id
